### ISSUE TITLE
Rename map to fmap for functors?

### ISSUE THREAD

**Issue by gyzerok** [fantasyland/fantasy-land#103]
What do you think about renaming map to fmap for functors. So we can eliminate confusion in this. The point is that map usually used to map collections, not single values.

Discussion starts from https://github.com/DrBoolean/mostly-adequate-guide/issues/122

**Comment by SimonRichardson** [comment]
I think it's been discussed a lot see #92

**Comment by SimonRichardson** [comment]
I would consider this a duplicate tbh.

**Comment by puffnfresh** [comment]
The point of map is to map. Haskell calls it fmap because it got things wrong.

**Comment by michaelficarra** [comment]
No way, `map` is a fine name. The only reason `fmap` exists in Haskell (as far as I know) is because the name `map` was already specialised to lists in Prelude, and generalising it would cause some problem specific to that language only. Maybe they would have to move Functor to Prelude? Anyway, it's just baggage that we have no reason to take on.

**Comment by bergus** [comment]
@michaelficarra Actually there would have been no problem with the language in Haskell, `Functor` already is in the Prelude. The only reason they didn't do this is that type errors would have gotten (much) more confusing, while `map` is one of the first basic operations that newbies learn.

**Comment by michaelficarra** [comment]
Ah, thanks. A possible solution to that would be a "beginner" mode of the compiler/standard libs. But I've not thought it through, so maybe that wouldn't be feasible.

**Comment by puffnfresh** [comment]
At best Haskell makes a sacrifice in the wrong name, at worst a false sacrifice in the wrong name. I think it's the latter.
