### ISSUE TITLE
Translating README.md of fantasyland into Japanese

### ISSUE THREAD

**Issue by PandaNoir** [fantasyland/fantasy-land#107]
I would like many people to know fantasyland. But many japanese don't read English. So I would like to introduce Fantasyland to japanese. Do you mind if I translate README.md of fantasyland into Japanese and put it on my blog?

**Comment by bergus** [comment]
No, we don't mind (at least I don't). Thanks for letting us know, and thanks for making fantasyland internationally known! That's never bad :-)
Just make sure to include proper attribution and a link back to this repo, and you should be fine - also check [the license](/fantasyland/fantasy-land/blob/master/LICENSE) even if it doesn't say anything about translations.

**Comment by PandaNoir** [comment]
I've done. https://github.com/PandaNoir/fantasy-land

**Comment by PandaNoir** [comment]
https://github.com/PandaNoir/fantasy-land/tree/japanese-translation

**Comment by SimonRichardson** [comment]
:+1:
