### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by suissa** [fantasyland/fantasy-land#108]
I´m doing this translation here https://github.com/Webschool-io/fantasy-land/ because i´m doing a free course about JS Functional.

Thanks for your work!

**Comment by 5outh** [comment]
Wow, excellent! Thank you! :100:

**Comment by SimonRichardson** [comment]
Generally, should we have a file that has links to translations or just close this, knowing there is one out there?

**Comment by SimonRichardson** [comment]
@suissa do you want to make a PR that has `translations.md` in the root and add your translation to it (similar to implementations.md).

**Comment by SimonRichardson** [comment]
Please make a PR containing the translations.md, so I'm closing this for now.
