### ISSUE TITLE
Use arrow functions

### ISSUE THREAD

**Issue by rpominov** [fantasyland/fantasy-land#109]
They are now [supported by latest Chrome, Opera, Edge, and Firefox](https://kangax.github.io/compat-table/es6/#arrow_functions). And I think most of JavaScript developers already familiar with them. Perhaps it makes sense to rewrite code snippets in spec using them.

A small example:

 1. `u.map(function(a) { return a; })` is equivalent to `u` (identity)
 2. `u.map(function(x) { return f(g(x)); })` is equivalent to `u.map(g).map(f)` (composition)

With arrow functions:

 1. `u.map(a => a)` is equivalent to `u` (identity)
 2. `u.map(x => f(g(x)))` is equivalent to `u.map(g).map(f)` (composition)

Should I make a PR?

**Comment by davidchambers** [comment]
I'd like to see this change.

**Comment by SimonRichardson** [comment]
I don't care either way, so go for it :+1:
