### ISSUE TITLE
Example id.js is incorrectly commented

### ISSUE THREAD

**Issue by branneman** [fantasyland/fantasy-land#111]
The spec in the `readme.md` currently defines these data structures with methods:
```
Apply - ap()
Applicative - of()
Monad
Traversable - sequence()
```

But when I look at the comments in the `id.js` file, the comments link some methods to different algebras:
```
Applicative - ap()
Monad - of()
Traversable - traverse()
```

As a beginner to algebraic data types this is very confusing to me, what is what? Maybe the `Id` container is out of date? For example, I'm currently wondering what the difference is between an Apply and an Applicative. If I implement `Container.prototype.ap`, is an instance of that container called an apply or an applicative? And would a Haskell programming give the same answer? Should it not be that obvious for senior functional programmers that this mistake could not be made? Or is this completely new ground in JS?

The [Identity container from ramda-fantasy](https://github.com/ramda/ramda-fantasy/blob/master/src/Identity.js) is incomplete as far as I can see, but nicely annotated and seems to be better in sync with the spec, am I correct?

I propose the spec and the example Identity type be aligned to avoid this kind of confusion. I think it's very important for them to stay in sync.

As an aside, I think it's a good idea to give the Id container a more prominent spot, like in the first few paragraphs, it's of great help next to a very abstract specification.

**Comment by bergus** [comment]
The diagram of the dependencies should help here:
![](https://raw.githubusercontent.com/fantasyland/fantasy-land/master/figures/dependencies.png)
Think of it as subclass relations: Every Apply is a Functor, every Chain is an Apply (and therefore a Functor) etc.

So `ap` is implemented by Apply, Chain, Applicative, and Monad data types,
and `of` is implemented by Applicative and Monad data types.

Yeah, the comments in id.js are a bit odd, though not completely wrong. `ap` probably was native to Applicative when we didn't have Apply in the past, putting `of` "only" in Monad is confusing though.

**Comment by branneman** [comment]
Would you accept a PR where I've corrected the comments to match the spec?

**Comment by bergus** [comment]
I'm not a contributor so technically I cannot, but I'm sure it would be welcome.

**Comment by puffnfresh** [comment]
@branneman I'm not sure what all the problems are but I did see that `ap` saying `Applicative` was wrong - a PR would be useful so that I can also see the other problems.

**Comment by branneman** [comment]
Ok, cool. PR is on it's way.

One more question when I look at [`Id.prototype.sequence`](https://github.com/branneman/fantasy-land/blob/master/id.js#L36): could the second argument (`of`) be implemented as well?
