### ISSUE TITLE
sequence: disagreement between documentation and implementation

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#113]
Documentation:

> A value which has a Traversable must provide a `sequence` method. The `sequence` method takes one argument:
>
>     u.sequence(of)

Example implementation:

> ```javascript
> // Traversable
> Id.prototype.sequence = function(f, of) {
>     return f(this.value).map(function(y){ return new Id(y); });
> };
> ```

Does the method expect one argument or two?

/cc @DrBoolean

**Comment by DrBoolean** [comment]
Looks like the implementation was left as traverse, but renamed to sequence. Should only take 1 arg
