### ISSUE TITLE
Commutable > Traversable?

### ISSUE THREAD

**Issue by DrBoolean** [fantasyland/fantasy-land#115]
Hello!

Over at rambda https://github.com/ramda/ramda/pull/1467#issuecomment-151715080

There has been some discussion of the names `sequence` and `traverse` and how `commute` seems to make more sense in general. The idea is that `traverse` should be saved for a different function.

If in favor of renaming `sequence` to  `commute`, what would the typeclass be called? I think Traversable is more or less ubiquitous among FP languages so it'd be a shame to rename.

Thoughts?

**Comment by joneshf** [comment]
I'm not in favor of this change. `traverse` is one of the few functions here that actually **has** a good name, and I feel it would be a regression in understanding to change the name.

`commute` describes what the types do, `traverse` describes what the function does.

This is good reading: https://www.cs.ox.ac.uk/jeremy.gibbons/publications/iterator.pdf

**Comment by DrBoolean** [comment]
You're damn right, hardy. I'm familiar with the paper, but I never thought of the word traverse that way
