### ISSUE TITLE
Ordering of parallel `chain`s

### ISSUE THREAD

**Issue by Twisol** [fantasyland/fantasy-land#12]
Sourcing from [a when.js issue](https://github.com/cujojs/when/pull/102#issuecomment-13680705):

```javascript
p.chain(f).chain(g);
p.chain(h);
```

In the presence of side-effects, the order of execution matters. If the order is FHG (i.e. breadth-first), and h has a side-effect, then g may be affected by a totally separate chain (and indeed, `p.chain(h)` could be in an entirely different part of the file).

We could [stick with precedent](https://github.com/pufuwozu/fantasy-land/issues/4#issuecomment-16313280) and push the concern downstream, but I want to at least raise the issue as something that should be considered *somewhere* along the line.

**Comment by SimonRichardson** [comment]
Each function should ideally be referential transparent and with lack of side effects. So I'm closing this as a part of the unspecified part of the specification.

Reopen if you disagree :8ball:

**Comment by puffnfresh** [comment]
@SimonRichardson :+1:
