### ISSUE TITLE
Namespaced prefixes — next step for resolving name clashes

### ISSUE THREAD

**Issue by rpominov** [fantasyland/fantasy-land#122]
So #92 was somewhat resolved with this PR #120

The next step is to eventually publish a version of `fantasy-land` npm package with namespaced prefixed names.

There are some questions to discuss though:

 - When do we release the new version? Should we wait until majority of libs migrate to the new approach, or should we release it right away so two versions will coexist allowing everyone to choose on which versions to depend in each particular case?
 - How the prefixed names should look like?

Maybe there more questions, these two is what came to my mind.

**Comment by rpominov** [comment]
I've faced a couple of problems with the new approach. Not sure where better to document them, hopefully this issue is fine.

1. `of` is a reserved word, we can't use it for a variable name. Workarounds are:
  
  ```diff
  - import {map, of} from 'fantasy-land'
  + import {map, of as just} from 'fantasy-land'
  ```
  ```diff
  - const {map, of} = require('fantasy-land')
  + const {map, of: just} = require('fantasy-land')
  ```
  ```js
  // Alternatively just import whole object to a variable
  import fl from 'fantasy-land'
  foo[fl.of](1)
  ```
  Maybe we could add an alias for `of` in index.js (e.g. `just`)

2. [Flow](http://flowtype.org/) doesn't support dynamic names for methods (neither via `class` syntax nor via `.prototype`):
  ```
  src/fantasy.js:34
   34:   [concat]( other:Stream<T> ): Stream<T> {
          ^ computed property keys not supported
  ```
  ```
  src/fantasy.js:147
  147: Stream.prototype[concat] = Stream.prototype.concat
       ^^^^^^^^^^^^^^^^^^^^^^^^ assignment of computed property/element. Indexable signature not found in
  147: Stream.prototype[concat] = Stream.prototype.concat
       ^^^^^^ Stream
  ```
  A workaround I found so far looks like this:
  ```js
  addFLmethods(Stream.prototype)

  function addFLmethods( proto:any ): void {
    proto[concat] = proto.concat
  }
  ```
  But this is only a workaround for adding methods to a class, in any case we bypass Flow type checking when will use those class instances. And in general dynamic names can be a problem for any static analysis tools like Flow/TypeScript/etc.

**Comment by rpominov** [comment]
I was thinking, maybe in the future we could start treating all this as a temporal measure for the transition period and go back to using hardcoded names but with prefixes.

**Comment by rpominov** [comment]
Another issue: how to use FL compatible libraries in the browser (e.g. in jsfiddle)? 
Options I see so far:
 1. We could make `fantasy-land` package [UMD](https://github.com/umdjs/umd) compatible. Consumers then could load in browser two UMD libs (FL itself, and the FL compatible lib) and they should work fine together (not sure though, I'm not really sure how dependencies work in UMD).
 2. Bundle `fantasy-land` as part of the browser build of the library. This is not a great idea, but still could work for things like jsfiddle as long as all FL libs that are used bundled the same version of FL.
 3. Fallback to hardcoded unprefixed names in browser build of the library (basically same as 2. with backward compat version of FL).

**Comment by SimonRichardson** [comment]
> hardcoded names but with prefixes

I'm still not convinced by this, because I don't use `ramda` or alternatives, so if we do prefix things it just means it's more of a pain for me and an extra barrier for using fantasy-land, the great thing about the spec is that it can be used in both!

```js
Functor.prototype['fl/map'] = function(f) {};
// As an example.
const f = ...
f['fl/map'](x => x);
```

I wonder if there is a way to have both without sacrificing anything?

> of is a reserved word, we can't use it for a variable name

But this is a tooling/linting issue not actual code issue, because running this doesn't cause any issues. So either we create an alias to solve the tooling/linting issue or we just change the name completely. I'm not a fan of `just`, I'd rather have `pure`.

**Comment by michaelficarra** [comment]
@rpominov `of` is *not* a reserved word. Did some tool fail or did you just make that assumption?

**Comment by rpominov** [comment]
@SimonRichardson @michaelficarra Yeah, you are right about `of`. Seems like only Flow has problems with it:

```
src/fantasy.js:4
  4: import {of} from 'fantasy-land'
             ^^ Unexpected token of
```

I'll open an issue in Flow repo...

**Comment by michaelficarra** [comment]
Thanks @rpominov. Please link it here when you do. I'm very interested.

**Comment by rpominov** [comment]
https://github.com/facebook/flow/issues/1340

**Comment by SimonRichardson** [comment]
:+1:

**Comment by samwgoldman** [comment]
One thing, you're right that Flow doesn't currently support computed keys in a number of scenarios, and can't in general, but in the specific cases where the string literal information can be known statically it's possible. We already support string literal types, which enable this feature. I'll take a look to see if we can easily support this use case.

**Comment by rpominov** [comment]
@samwgoldman That would be great! So yeah computed names are just strings that comes from this file [index.js](https://github.com/fantasyland/fantasy-land/blob/master/index.js) I think it could be statically analysed, at least theoretically :)

**Comment by Avaq** [comment]
> I wonder if there is a way to have both without sacrificing anything?

[In Fluture](https://github.com/Avaq/Fluture/blob/master/fluture.js#L507-L508) I did this thing where I create keys for both `'map'` and `FL.map` on my type, so when FL adds namespaces, my API won't change, and FL dispatchers will still work.

**Comment by rpominov** [comment]
I think this the best way to do it, create normal methods in your API like with "old" FL, and then do something like:

```js
Type.prototype[FL.map] = Type.prototype.map
Type.prototype[FL.ap] = Type.prototype.ap
...
```

We could even provide a helper that does this automatically:

```js
import {makeFantasyLandCompatible} from 'fantasy-land/compat-helper'

makeFantasyLandCompatible(Type)
```

**Comment by isiahmeadows** [comment]
Just a curious question: why isn't `Symbol.for` being used? I feel something like exporting `Symbol.for("fantasy-land/ap")` may work fairly well, since `Symbol.for` is required to work cross-realm per ES2015+ spec.

**Comment by rpominov** [comment]
Symbols may cause some pain in legacy JS environments. Also Flow doesn't currently support Symbols for instance.

On the other hand it's not clear how `Symbol.for("fantasy-land/ap")` better than just `"fantasy-land/ap"` for our use-case.

**Comment by Avaq** [comment]
More discussion on the subject of `Symbol.for('fantasy-land/x')` can be found [here](https://github.com/fantasyland/fantasy-land/pull/146#issuecomment-238163553)

**Comment by isiahmeadows** [comment]
@rpominov I came up with a possible solution to that [here](https://github.com/fantasyland/fantasy-land/pull/146#issuecomment-239562454).

But I'm still trying to see why namespacing is even necessary at all. Reading the previous discussion on namespacing the methods hasn't really convinced me.

**Comment by SimonRichardson** [comment]
This is done.

**Comment by rpominov** [comment]
@samwgoldman We now have switched to constant prefixed names, which Flow can support but unfortunately [doesn't yet](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsASQBMAeAFQD4wBvVMMAfQA8AuMcgbnrAzgDtcAFwBOAVwxC4IgBRsOASlo8GQgBYBLXADoWYALxhmPAL49h2IRoxg4UCpTntyC9iQfKGDEQFMhYkX4wfh8kEjkFU3MhS2swAHIobH4Y3ABPAFocfmJgO3iHJ0U3MipPL19-QODQomIIqJMgA).

**Comment by rpominov** [comment]
Opened an issue in Flow repo https://github.com/facebook/flow/issues/2482
