### ISSUE TITLE
Generators, monad comprehensions, and then

### ISSUE THREAD

**Issue by DrBoolean** [fantasyland/fantasy-land#125]
Perhaps we should rename `chain` to `then`?

That allows syntax like:

```js
const co = require('co');
const daggy = require('daggy')

const Maybe = daggy.taggedSum({Just: ['x'], Nothing: []})

Maybe.prototype.then = function(f) {
  return this.cata({
    Just: x => f(this.x),
    Nothing: () => this
  })
}

co(function *() {
  const four = yield Maybe.Just(4)
  const two = yield Maybe.Just(2)
  console.log(four + two)
})
```

https://www.youtube.com/watch?v=SPgPhKLE1wg

**Comment by SimonRichardson** [comment]
@DrBoolean nice - having seen this, it makes me wonder if `fantasy-land` should rename `Promise` to `Task` as I'm seeing confusion arising in the future.

I like the idea of being able to use this with generators, but I'm wonder if it would be better served writing a interpolation specification for `then`? The issue I have with `then` is that it breaks the specification i.e. `F a -> (a -> F b) -> F b`, most seem to do `F a -> (a -> b) -> b` or even `F a -> (a -> ()) -> ()`

Most implementations could even just alias `chain`, but there are rare occasions that this might not be [ideal](https://github.com/fantasyland/fantasy-frees/blob/master/src/free.js#L27).

In the end, I don't really care, but I would hope that if I called `chain` it does what I require, if that's the case then I'm ok with it in the end.

**Comment by rpominov** [comment]
Alternatively someone could create a fork of `co` that works with FL monads.

**Comment by SimonRichardson** [comment]
https://github.com/tj/co/blob/master/index.js#L198 or just add the following:

```js
function isPromise(obj) {
  return 'function' == typeof obj.then || 'function' == typeof obj.chain;
}
```

**Comment by SimonRichardson** [comment]
Also tbh I think most of what `co` is doing could be removed because we actually know what a function/structure returns and so the wide number of side effects this library tries to mitigate against can be reduced a great deal.

**Comment by DrBoolean** [comment]
Good thinking! I fully agree that it should remain `chain`. The alias is good enough for my purposes.
