### ISSUE TITLE
0.2.0 release should be done

### ISSUE THREAD

**Issue by pandanoir** [fantasyland/fantasy-land#126]
fantasy-land 0.2.0 was released in 900f84178d618977847c00421e1a915a384e7b4 ! Wonderful update!

However, 0.2.0 release hasn't been published yet. https://github.com/fantasyland/fantasy-land/releases

Because there is 0.1.0 release, 0.2.0 should be released, isn't it?

**Comment by SimonRichardson** [comment]
https://github.com/fantasyland/fantasy-land/releases/tag/v0.2.1
