### ISSUE TITLE
Library of Haskell functions in ES2015 (similar to this library)

### ISSUE THREAD

**Issue by sjsyrek** [fantasyland/fantasy-land#129]
I recently published a JS library with some similar functionality to this library, if not as comprehensive, and in ES2015. So it's still experimental and incomplete, but it may be of interest to people:
[maryamyriameliamurphies.js](https://github.com/sjsyrek/maryamyriameliamurphies.js)

**Comment by CrossEye** [comment]
Thank you.  It looks interesting, and worth a look, and I'm going to blame you if I forever more hear the word 'Applicative' in an Irish brogue.

JFTR, this is not a library, but a specification, although there are a number of [related libraries][fl] nearby.


  [fl]: https://github.com/fantasyland

**Comment by sjsyrek** [comment]
"Blame" or "thank"? 🍀

**Comment by SimonRichardson** [comment]
Closing this as I'm not entirely sure what to do with this? :sheep:

**Comment by joneshf** [comment]
I'd like to think we could add it to the implementations file. but i"m not exactly clear on the api the data types provide. I'd also like if we could come together on a similar api for most things.

@sjsyrek thoughts?

**Comment by sjsyrek** [comment]
@joneshf I wrote maryamyriameliamurphies to imitate Haskell functions, so the API is really just a bunch of functions (listed in the README). I would definitely like to make the documentation clearer, though, if it's confusing. Maybe what's strange in a JS context is that I'm not exporting the data types themselves but only the operations over them? In that sense, my API could be incompatible with the Fantasy Land spec, since I'm adhering to the Haskell way of doing things and not just implementing algebraic data types in general.
