### ISSUE TITLE
"Apply's ap; derivable as" mentioned in both Chain and Monad

### ISSUE THREAD

**Issue by rpominov** [fantasyland/fantasy-land#133]
Is this intentional? Monad depends on Chain anyway, so it seems redundant.

Also I noticed it says "Apply's ap" not "Applicative's ap", so with Chain or Monad we only get Apply for free, not Applicative?

Just a thought: maybe there should be duplication, but in Monad it should say "Applicative's ap"?

**Comment by CrossEye** [comment]
I'm not sure what you're saying.  `ap` is defined by the `Apply` spec.  So if `ap` is derivable, it's "the `ap` method of `Apply`" or "`Apply`'s `ap`" that we would discuss.  With `Chain`, we do not get `Applicative` for free.  (There are non-`Applicative` `Chain`s, and `Applicative`s that are not `Chain`s.)  With `Monad`, we must implement both `Chain`'s `chain` and `Applicative`'s `of`, but we can derive `Apply`'s `ap`.

**Comment by rpominov** [comment]
That makes sense I came to the similar conclusion after thinking more about it. The only thing that bugs me now is:

 > Monad depends on Chain anyway, so it seems redundant.

**Comment by CrossEye** [comment]
Yes, that is a bit redundant.

**Comment by rpominov** [comment]
Fixed by https://github.com/fantasyland/fantasy-land/pull/134
