### ISSUE TITLE
[proposal] Add type signatures to the spec.

### ISSUE THREAD

**Issue by scott-christopher** [fantasyland/fantasy-land#138]
While writing up #137 I found that a type signature could potentially help convey some of the restrictions in a clearer and more succinct manner, especially around notions of covariance and contravariance.

I'd propose adopting the Haskell-ish signature format that appears to be at least somewhat common in the Fantasy Land space, where the method target type appears between the type constraints and the function argument types, separated by a `~>`.

e.g.
```hs
sequence :: (Traversable t, Applicative f) => t (f a) ~> (a -> f a) -> f (t a)
```

Happy to open a PR if there's any interest in this.

**Comment by davidchambers** [comment]
I would certainly appreciate this addition!

**Comment by rpominov** [comment]
This would make spec much easier to read and understand. Not sure if it can be helpful but I took this approach in [static-land](https://github.com/rpominov/static-land/blob/master/docs/spec.md).

**Comment by SimonRichardson** [comment]
If you want to do this, just make a PR, I'm pretty sure it will be signed off without a hitch!

**Comment by SimonRichardson** [comment]
This has been done!
