### ISSUE TITLE
publish to Bower registry

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#139]
I'd like to use the exported method names in projects which target browsers (in addition to Node). In order to do so, we must first:

1.  add environment detection to __index.js__, and export as `window` property in browser context;
2.  add __bower.json__; and
3.  run `bower register fantasy-land git://github.com/fantasyland/fantasy-land.git`.

I'll submit pull requests for 1 and 2 if maintainers are on board. :)

**Comment by SimonRichardson** [comment]
@davidchambers can you make a PR.

**Comment by davidchambers** [comment]
@SimonRichardson, you can perform step 3 now. :)

**Comment by SimonRichardson** [comment]
This is done now!
