### ISSUE TITLE
Changing ap arguments order for consistency with map and chain, and for better types support

### ISSUE THREAD

**Issue by rpominov** [fantasyland/fantasy-land#144]
The current order of arguments (if we count `this` as an argument) in `ap` is problematic. I see two problems about it.

### It's inconsistent with `map` and `chain`

```
map :: (this: A, f: A => B) => MyType<B>
chain :: (this: A, f: A => MyType<B>) => MyType<B>
ap :: (this: MyType<A => B>, x: MyType<A>) => MyType<B>

// sorry about made up types lang, I hope it's clear what I mean here
```

In `map` and `chain` value goes first and function goes second, in `ap` the other way around.

### It's impossible to type with Flow and probably other type systems

... or at least hard, and I didn't figured out how to do it.

```js
// @flow

// With current arguments order we have to use `any`, and therefore loose type info
class MyType<A> {
  ap(other: MyType<any>): MyType<any>
}

// With reversed order it's straightforward
class MyType<A> {
  ap<B>(other: MyType<A => B>): MyType<B>
}
```

I understand this is a braking change that will probably break a lot of code. But I just want to open this discussion, and hear what others think. Maybe this is a pain point for many people, and it would be reasonable to make the change.

**Comment by SimonRichardson** [comment]
It's been mentioned before, I'll dig out the references, but I'm in favour as well.

**Comment by SimonRichardson** [comment]
https://github.com/fantasyland/fantasy-land/issues/50#issuecomment-27708812

**Comment by rpominov** [comment]
Ah, right. #50 is specifically about this problem. I remember it was mentioned before, but thought that it was mentioned briefly in an unrelated issue. I guess I created a duplicate then, sorry. I'll close this one.

**Comment by SimonRichardson** [comment]
Let's do it, open a PR.

**Comment by rpominov** [comment]
OK, I'll open one tomorrow.
