### ISSUE TITLE
Contravariant Functor?

### ISSUE THREAD

**Issue by rjmk** [fantasyland/fantasy-land#149]
Copied from https://github.com/rpominov/static-land/issues/15

> Would [fantasyland] be interested in a contravariant functor added to the spec?

> It would have a method contramap :: Contravariant f => (a -> b, f b) -> f a. It would become a dependency to profunctor. The laws are pretty much the same as for functor, but with a flip on the functions in composition

> Happy to make a PR for [people] to look over

**Comment by SimonRichardson** [comment]
:+1:

**Comment by rpominov** [comment]
Probably one of reasons why this didn't happen from the beginning is that we didn't want to claim another name for FL in people's methods namespaces. If that was the case, then this is another argument for #146 .

**Comment by SimonRichardson** [comment]
Closing this as the discussions are now in the PR. Reopen if you think otherwise.
