### ISSUE TITLE
export curried functions

### ISSUE THREAD

**Issue by safareli** [fantasyland/fantasy-land#155]
I think it would be nice to also export curried functions for example:
```diff
-m[fl.map](f)
+fl.map(f, m)
```

**Comment by SimonRichardson** [comment]
https://github.com/fantasyland/fantasy-sorcery/blob/master/index.js#L16

**Comment by safareli** [comment]
This also looks interesting https://github.com/sanctuary-js/sanctuary-type-classes/pull/2
