### ISSUE TITLE
The new Apply spec

### ISSUE THREAD

**Issue by evilsoft** [fantasyland/fantasy-land#169]
## Did I take Crazy Pills?
![](https://media4.giphy.com/media/AbPWwqSgMejM4/200_s.gif)

More of a question than an actual issue. I think I may be missing something with the new Apply spec updated a wee bit ago. So I started to make updates to my project to reflect this change and it seems to me like this change is limiting the API. Just want to make sure I have this right. So an Identity used to be:

``` javascript
function Identity(x) {
  const map = fn => Identity(fn(x))
  const value = R.always(x)
  const ap = m => m.map(x)

  return { map, value, ap }
}
```

and I could "chain" it outside of a lift function as:

``` javascript
// data === Identity 8
const data =
  Identity(add)
    .ap(Identity(3))
    .ap(Identity(5))

// or

// data === Identity 8
const another =
  Identity(3)
    .map(add)
    .ap(Identity(5))
```
Never have to extract in the container and I have the option of having one of the parameters do the lifting for me through `map`, if I choose to.

But if I am reading the spec correct it means it all looks and feels like this now:
``` javascript
function Identity(x) {
...
  const ap = m => Identity(m.value()(x))
...
}

const data =
  Identity(4)
    .ap(
      Identity(5)
        .ap(Identity(add))
    )
```

Now am I missing how to use this? It seem like I lose the ability to "chain" and am always stuck with this composing interface. So if I am reading that right it seems that we lose the ability to choose how our flows are constructed and either have to provide our users lift functions to hide all of this away from them, or limit them to this interface.

Now I am *very* new at this, so I am probably missing something really cool and clever here. But I guess I have two questions:

1. What is the value of making this change? (or why was it wrong to begin with)
1.  Is there a better way to use this outside of writing liftAN functions.

**Comment by evilsoft** [comment]
Sorry that example was kinda ugly and strawman-ish it can be used like this of course:
``` javascript
const data =
  Identity(4)
    .ap(Identity(5).map(add))
```

but I still have to compose here, yeah?

**Comment by evilsoft** [comment]
### Maybe I'm old fashioned...
![](http://i.imgur.com/nt4ozy9.gif)

The one thing I really enjoyed about that crusty old `ap` being different than `map` and `chain` is that if I ever found myself with function on the left, i knew that she would be there for me, to set things straight. I could always rely on her to take value and do what is right with it. And continue on until a value resulted.

But now if I ever end up with a function on the left, I have no recourse other than some fancy arrangement through composition.

(this is the last comment I swear!!)

**Comment by evilsoft** [comment]
Well, I mean, I guess I can clean it up by using `thrush`.
Is this what you had in mind when we have a function on the left?

```javascript
const thrush =
  x => fn => fn(x)

const data =
  Identity(4)
    .map(add)
    .ap(Identity(thrush(5)))
```

**Comment by davidchambers** [comment]
> What is the value of making this change?

Consistency.

Before:

```haskell
map   :: Functor f => f a        ~>   (a -> b) -> f b
ap    ::   Apply f => f (a -> b) ~>        f a -> f b
chain ::   Chain f => f a        ~> (a -> f b) -> f b
```

After:

```haskell
map   :: Functor f => f a ~>   (a -> b) -> f b
ap    ::   Apply f => f a ~> f (a -> b) -> f b
chain ::   Chain f => f a ~> (a -> f b) -> f b
```

**Comment by evilsoft** [comment]
Yeah :corn:sistancy makes a lot of sense.
I think I always though of `ap` being synonymous to the A combinator, allowing me to apply a value to a function and I always thought of `map` as a way to apply an function to a value (no offense to `map`).

Are there any plans to add an algebra that will allow the application of a value to function?

Also, I may stick with the old version of the spec, is there a way to signal that I am keeping `ap` in the old spec, but still bring in the new hotness like traverse over sequence, etc. Or am I stuck in the old spec fully?

**Comment by SimonRichardson** [comment]
Currently there aren't any plans to update the old spec. Mainly from lack of time on my part and inconsistencies that any new changes would bring. Also it wouldn't be fair on you if I did say "yes" and not do anything medium to long term.

Personally I think the new `ap` is more consistent and easier to reason about. There isn't anything stopping you from making your own `apʹ` that did what you wanted.

**Comment by evilsoft** [comment]
Awesome. You have all answered my questions.

Think the best route for me to take is to update `ap` to the new spec, and provide another function that flips the script and allows what my ❤️  desires.

That way I can still earn my sticker and get what I want. The whole have my 🍰  and eat it too situation.

Thanks so much for your time and hard work on this spec. 
Is it cool for me to close this issue out, or do you like to do that?

**Comment by SimonRichardson** [comment]
There you go 👍
