### ISSUE TITLE
cannot use laws/monad to test left identity property

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#170]
I'm trying to use the `fantasy-land/laws` in a test suite for the first time. I've hit a snag.

The spec defines the left identity property of Monad as follows:

> `m.of(a).chain(f)` is equivalent to `f(a)` (left identity)

Here's the accompanying [`leftIdentity`][1] function:

> ```javascript
> const leftIdentity = t => eq => x => {
>     const a = t[of](x)[chain](identity);
>     const b = identity(x);
>     return eq(a, b);
> };
> ```

If we assume that the `a` in `m.of(a).chain(f)` is of type `a`, then the type of `f` must be `a -> m b`. The identity function is only suitable if `x :: m (m c)`, such as `[[1], [2], [3]]` or `Just(Just(42))`. My understanding, though, is that there's an implicit `forall x.`, so `f` is constrained rather than `x`. If my understanding is correct, `leftIdentity` is dysfunctional. It seems `leftIdentity` needs to take an additional argument, `f :: a -> m b`.

[1]: https://github.com/fantasyland/fantasy-land/blob/1.0.1/laws/monad.js#L15-L19

**Comment by SimonRichardson** [comment]
Probably, I definitely made mistakes when I ported them over. I'd be more than happy to have  PR for the fix.
