### ISSUE TITLE
add flyd to implementations.md?

### ISSUE THREAD

**Issue by leeoniya** [fantasyland/fantasy-land#194]
Hi,

flyd [1] claims to be `fantasy-land`-compatible (have not verified if this is actually the case), perhaps add it to implementations.md ?

[1] https://github.com/paldepind/flyd

**Comment by rpominov** [comment]
It doesn't seem to be compatible with fantasy-land@1.0 (does not use prefixed names for properties for instance).

Although `implementations.md` contain a lot of libraries that are not compatible with newer versions of FL, I think.

**Comment by davidchambers** [comment]
> Although `implementations.md` contains a lot of libraries that are not compatible with newer versions of FL, I think.

Good point. Perhaps we should make it clear that these libraries support early versions of the spec, and request that their authors submit pull requests to update the document if and when a library is updated to work with v2.x.x.

**Comment by SimonRichardson** [comment]
I'm starting to think we should drop `implementations.md`! 😱  It's going to be a nightmare to keep up to date in the future especially if we're going to move forward at this pace! 

Although I'd be more than happy to if someone 'owned' it and took it on themselves to keep it up to date, I don't think asking authors to submit PRs to keep it up to date is going to cut it.

**Comment by rpominov** [comment]
Just one more way we can go is to make this a GitHub wiki document, so authors could easily edit it. Still won't solve the problem of keeping it up to date completely though.

**Comment by rpominov** [comment]
Also we could use npm for this as suggested in https://github.com/fantasyland/fantasy-land/pull/168#issuecomment-248894913

We could recommend authors to add `fantasy-land` as a keyword if they don't want to add it as a dependency, and then we could use this list https://www.npmjs.com/browse/keyword/fantasy-land

**Comment by paldepind** [comment]
Yes, flyd does not support 1.0. I'd probably not want to change that before Ramda supports 1.0.
