### ISSUE TITLE
Order of Traversable parameters

### ISSUE THREAD

**Issue by evilsoft** [fantasyland/fantasy-land#198]
## About to be so embarrassed

![giphy](https://cloud.githubusercontent.com/assets/3665793/19828171/21f316c6-9d74-11e6-8a7c-b283844df9ba.gif)

Wondering if the order of traverse should be reversed...

Hear me out here and please join on this journey. If you will.

If I were to think about the stability of the arguments, it would make sense that the most stable of the two is the Just-In-Case (or the `empty` on a List sequence) Applicative and the least stable would be that little cutie that transforms and lifts. 

If you look at some of the point-free offerings out there, like Ramda's for instance, it just seems natural. One seems to get more play out of that family of functions when the optional boy is first. While yes it is for special cases and because well Javasctipt, it is required and usually is the same for a whole slew of functions.

So if I have:
``` javascript
// traverse : (c -> f c) -> (a -> f b) -> t a -> f (t b)

const traverseMaybe = 
  traverse(Maybe.of)

// badJohn : String -> Maybe String
const badJohn =
  ifElse(equals("John"), Nothing, Just)

// sillyNumber : Number -> Maybe Number
const sillyNumber =
  ifElse(equals(1337), Nothing, Just)

// safePeeps : [ String ] -> Maybe [ String ]
const safePeeps = 
  traverseMaybe(badJohn)

// seriousNumbers : [ Number ] -> Maybe [ Number ]
const seriousNumbers = 
  traverseMaybe(sillyNumber)
```

The only reason I bring this up is YES, yes I can write that point-free auto partial application helper anyway that suits me and NO I should probably allow for partial application directly on my ADT functions with more than one argument. But it sure can come in handy when working inside of the container. Right now I am resorting to doing a `flip` on that when not working with my point-free function.

What is the reasoning behind that argument order? Would you see any value in flipping them to what seems to be a more intuitive order (IMO of course)?

**Comment by davidchambers** [comment]
With partial application in mind [`Z.traverse`][1] takes `of` first, as you're suggesting.

> What is the reasoning behind that argument order?

Perhaps the thinking was that `of` isn't always required; it can be omitted from some method definitions as a result of being the last parameter. I don't find this compelling, though.

The methods in the spec are not curried. For [sanctuary-type-classes][2]<sup>†</sup> it's not difficult to provide a function which takes arguments in one order and provides them to the appropriate method in another order. I don't think we should make a breaking change here.

---

† I'm hopeful that the community will embrace this as the "standard library" for Fantasy Land. We don't need multiple subtly different libraries which simply wrap Fantasy Land methods.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes#traverse
[2]: https://github.com/sanctuary-js/sanctuary-type-classes

**Comment by evilsoft** [comment]
I figured as much. Figured I would throw it up the flag pole and see who salutes. I would have been remiss has I not proposed it.

Closing and moving another step away from this spec. 😢

**Comment by joneshf** [comment]
I dont see any reason we cant change that. Feel free to reopen.
