### ISSUE TITLE
Add Ramda-Fantasy to implmentations?

### ISSUE THREAD

**Issue by EvanBurchard** [fantasyland/fantasy-land#201]
I'm not sure if this has been discussed already. Is [Ramda-Fantasy](https://github.com/ramda/ramda-fantasy) a conformant implementation?

If not, does anyone here know why? Or should I ask on that repo?

**Comment by davidchambers** [comment]
As with #194, ramda-fantasy supports *a* version of the FL spec but not the current one. ramda/ramda-fantasy#131 will bring it to v1.0.x if merged, but FL is now at v2.1.0. ;)

**Comment by EvanBurchard** [comment]
@davidchambers Thanks for catching me up.
