### ISSUE TITLE
Please review my blog post series on FP

### ISSUE THREAD

**Issue by rajaraodv** [fantasyland/fantasy-land#202]
Hi there,
It would be great if you can do a quick review of my blog post series on FP. My whole objective is to make FP more accessible and popular. Below are links to 2 parts. I plan to write more depending on how this goes.

**Making corrections:**
To make corrections, simply select the text and click on the "lock icon". It allows you to add private comments on the Medium itself.

Functional Programming In JS — With Practical Examples (Part 1)
https://medium.com/@rajaraodv/functional-programming-in-js-with-practical-examples-part-1-87c2b0dbc276

Functional Programming In JS — With Practical Examples (Part 2)
https://medium.com/@rajaraodv/functional-programming-in-js-with-practical-examples-part-2-429d2e8ccc9e

**Comment by safareli** [comment]
you could use [glitter](gitter.im/fantasyland/fantasy-land) channel for that i think.
One thing I noticed is that the Maybe monad you have is not lawful Monad.
- it is violating Monads `M.of(a).chain(f) is equivalent to f(a) (left identity)` law

    when  `a = null` and `f = _ => 1`
- it is violating Functor `u.map(x => f(g(x))) is equivalent to u.map(g).map(f) (composition)` law

    when`g = _ => null`, `f = _ => 1` and `u =  new Maybe(null)`
- And i think it is also violating all Applicative laws

**Comment by SimonRichardson** [comment]
Yeah, it's important that we fix this, as it's also wrong and the one most people do get wrong! You've implemented `m a ~> (a -> m b) -> m b` and not `f a ~> (a -> b) -> f b`

```js
class MyFunctor { //Custom "Functor"
  ...
  map(fn) {   //<-- This simply applies a function on the value.
   return fn(this.val);
  }
}
```

**Comment by SimonRichardson** [comment]
Can we also *stop* re-implementing the `Maybe`/`Option` type. Your example is wrong in so many ways, I would rather you copied one from an existing library and showed that (with correct credits). 

You should *not* differentiate between `null` or `undefined` for `Maybe`, as `Maybe(null)` is a valid type. What you could do is provide a `Maybe.fromNullable()` that projects it into the correct type that you want, but it's not something you should do in the `type` as you break laws associated to the type.

**Comment by rajaraodv** [comment]
Thanks @safareli and @SimonRichardson! I've fixed both. Please let me know if there is anything else.

**Comment by rpominov** [comment]
I think we should close this, because it's a discussion that cannot be *resolved*.

**Comment by safareli** [comment]
@rajaraodv  after you have updated Maybe implementation to lawful one your examples might be broken now
```js
.map(path(['prefs', 'languages', 'primary']))
// here `path` might return `null` 
```
