### ISSUE TITLE
Is concurrent Alternative instance for Task|Future Monad lawful?

### ISSUE THREAD

**Issue by safareli** [fantasyland/fantasy-land#203]
[My initial intuition](https://github.com/fantasyland/fantasy-land/issues/187#issuecomment-255369874) was that (as of `ap = <*>`) Alternative intance of Task|Future Monad should be something like [this](https://github.com/slamdata/purescript-aff/blob/7ee09140f36c52d6d8c489b811d41133b9d45129/src/Control/Monad/Aff.purs#L192-L198) (from purescript-aff) and it should not be implemented using **never and race**. but today i came across https://github.com/briancavalier/creed/pull/92 and there Alternative is implemented using **never and or(aka race)**. After thinking for a while it looks lawful, only issue i see (which actually might not be an issue), is that with distributivity law `x.ap(f.alt(g)) == x.ap(f).alt(x.ap(g))`
- in left branch, function from **either** `f` or `g` will be called 
- in right branch, function from **both** `f` or `g` will be called

But as function in `g` should be pure it might not be an issue? If that's an issue, then `Maybe` also has this same issue (which I think is not present in Haskell because of laziness)

possibly related issues:
- https://github.com/Avaq/Fluture/issues/44
- https://github.com/origamitower/folktale/issues/52
- https://github.com/slamdata/purescript-aff/issues/5
- https://github.com/fantasyland/fantasy-land/issues/179

**Comment by safareli** [comment]
@jdegoes @garyb you have been maintaining `Purescript-Aff`, maybe you have an answer

**Comment by jdegoes** [comment]
The Alternative instance of Task|Future must run the first, if it fails, run the second — in sequence.

The Alternative instance for a Parallel must run both, at the same time, and return the first one which succeeds.

**Comment by safareli** [comment]
@jdegoes  yes, that was my initial intuition, but which law is reason for that?

**Comment by jdegoes** [comment]
The laws are here: https://en.wikibooks.org/wiki/Haskell/Alternative_and_MonadPlus

They don't look like they force these, but they look compatible with them. Good question though.
