### ISSUE TITLE
Apply composition law does not equate

### ISSUE THREAD

**Issue by jlmorgan** [fantasyland/fantasy-land#209]
It could be that my implementation is not correct, but here's the result of the test.

### test.js

```javascript
"use strict";

class Thing {
  constructor(value) {
    this.value = value;
  }
  ap(other) { return other.map(this.value); }
  map(f) { return new Thing(f(this.value)); }
}

const y = new Thing(x => x);
const left = y.ap(y.ap(y.map(f => g => x => f(g(x)))));
const right = y.ap(y).ap(y)

console.log("left === right:", left === right);
console.log("left value:", left.value.toString());
console.log("right value:", right.value.toString());
```

### Running test.js

```bash
$ node test
left === right: false
left value: g => x => f(g(x))
right value: x => x
```

**Comment by davidchambers** [comment]
First, you shouldn't expect to be able to compare your values with `===`. You'll need to define a [`fantasy-land/equals`][1] method. Secondly, `y.ap(y)` is correct (I think) but quite confusing. One *can* provide `identity` as an argument to `identity` (`identity(identity)`) but I think it wise to start with more straightforward applications such as `Math.sqrt(9)`. For example:

```javascript
'use strict';

var Z = require('sanctuary-type-classes');

function Thing(value) {
  if (!(this instanceof Thing)) return new Thing(value);
  this.value = value;
}

Thing.prototype.equals =
Thing.prototype['fantasy-land/equals'] = function(other) {
  return Z.equals(this.value, other.value);
};

Thing.prototype.ap =
Thing.prototype['fantasy-land/ap'] = function(other) {
  return Thing(other.value(this.value));
};

Thing.prototype.inspect =
Thing.prototype.toString = function() {
  return 'Thing(' + Z.toString(this.value) + ')';
};

Thing(9).ap(Thing(Math.sqrt));
// => Thing(3)

Z.ap(Thing(Math.sqrt), Thing(9));
// => Thing(3)
```

I hope this proves helpful. :)


[1]: https://github.com/fantasyland/fantasy-land#equals-method

**Comment by safareli** [comment]
- `ap` is incorrect it should be `ap(other) { return this.map(other.value); }`.
- you should read about [Comparison operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators)

**Comment by safareli** [comment]
also read about [Comparison operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) in JS

**Comment by jlmorgan** [comment]
My presumption on how `.ap` was suppose to work and what the test implied was that if the final value would ultimately just be the original identity function being passed along. Your correction to the implementation of `.ap` alters that perception as now the composition has more of an affect on the computation resulting in a differing function reference.

```javascript
const y = new Thing(x => x);
const left = y.ap(y.ap(y.map(f => g => x => f(g(x)))));
const right = y.ap(y).ap(y)
```

Something that would help immensely when learning this material is not having to learn Haskell in order to read JavaScript. Function signatures actually _in_ JavaScript would help greatly. I understand that JS doesn't have types, but those things can be inferred through annotations or jsdoc stuffs.

On a side note, thanks to all for providing this reference project. = D

**Comment by jlmorgan** [comment]
So, for a brief moment on here, I saw:

```
ap(other) { return this.map(other.value); }
```

and above he has:
```
ap(other) { return other.value(this.value); }
```

which is it?

**Comment by safareli** [comment]
you can fix your original `ap` this way too:
```diff
-  ap(other) { return other.map(this.value); }
+  ap(other) { return this.map(other.value); }
```
and if you inline definition of `map` you get:
```js
ap(other) { return other.value(this.value); }
```

**Comment by davidchambers** [comment]
> Function signatures actually _in_ JavaScript would help greatly. I understand that JS doesn't have types, but those things can be inferred through annotations or jsdoc stuffs.

[sanctuary-def][1], unlike TypeScript, can accurately express the type of `ap`. It's pretty noisy, though! I think learning to read Haskell type signatures is a better use of time than learning how sanctuary-def works. ;)

Haskell:

```purescript
ap :: Apply f => f (a -> b) -> f a -> f b
```

JavaScript:

```javascript
//    a :: Type
const a = $.TypeVariable('a');

//    b :: Type
const b = $.TypeVariable('b');

//    f :: Type -> Type
const f = $.UnaryTypeVariable('f');

//    ap :: Apply f => f (a -> b) -> f a -> f b
const ap = def('ap', {f: [Z.Apply]}, [f($.Function([a, b])), f(a), f(b)], Z.ap);
```


[1]: https://github.com/sanctuary-js/sanctuary-def

**Comment by jlmorgan** [comment]
So, does this mean that the intention of `ap` is to apply boxed functions to a boxed value? In a sense where `[Apply]` is a box, `add1` increments, and `mul2` multiplies by 2:

```
[Apply 1].ap([Apply add1]).ap([Apply mul2]) -> [4]
```

**Comment by davidchambers** [comment]
You may find the examples for [`Z.ap`][1] instructive, @jlmorgan. I find Haskell examples clearer, though:

```haskell
λ [(*10),(*100),(*1000)] <*> [1,2,3]
[10,20,30,100,200,300,1000,2000,3000]
```

`<*>` is the name for `ap` in Haskell. It takes the "thing" of functions as its left operand and the "thing" of arguments as its right operand.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes#ap

**Comment by joneshf** [comment]
`ap` exists in Prelude as well.

```haskell
λ: ap [(*10),(*100),(*1000)] [1,2,3]
[10,20,30,100,200,300,1000,2000,3000]
```

**Comment by davidchambers** [comment]
I didn't know that, Hardy. Thanks for the tip. :)

I'll close this issue as there's nothing to fix or change, but feel free to keep commenting.

**Comment by SimonRichardson** [comment]
:+1:

**Comment by jlmorgan** [comment]
When I read the above code with the mindset of function first, it make me think the following should occur:

```javascript
const mul = left => right => left * right;

Thing(mul(100)).ap(Thing(2));
// => [Thing 200]
```
And not how it seems implemented above which is more like:

```javascript
Thing(2).ap(Thing(mul(100));
// => [Thing 200]
```

Thinking function-first, data-last would seem to suggest that the function would be boxed first, then applying values to that function. Similar to `Function#apply` or a curried `Function#call`.

**Comment by davidchambers** [comment]
> Similar to `Function#apply` or a curried `Function#call`.

Don't contaminate your thoughts with this sort of comparison. ;)

I suggest comparing `ap` to `map`. They're very similar:

```javascript
> Thing(9).map(Math.sqrt)
Thing(3)

> Thing(9).ap(Thing(Math.sqrt))
Thing(3)
```

The type signatures are instructive:

```purescript
map :: Functor f => (a -> b) -> f a -> f b
ap  :: Apply f => f (a -> b) -> f a -> f b
```

**Comment by joneshf** [comment]
> Also, where's a good place to have interactive conversations with people that know both sides of this well enough? I have other questions and don't want to drag on this "issue" too much.

As @davidchambers mentioned, please feel free to continue the discussion in this issue if you'd like. If you want more real-time communication you can join the gitter channel: https://gitter.im/fantasyland/fantasy-land

**Comment by joneshf** [comment]
> I didn't know that, Hardy. Thanks for the tip. :)

I think that's actually where `ap` comes from. :)

**Comment by xgrommx** [comment]
@joneshf `<*>` == `ap` and also `ap` doesn't exists in Prelude, `ap` contains in `Control.Monad`
