### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#216]
When linking to a particular section of the FL spec one should really include the name of an annotated tag in the URL. Otherwise there's no guarantee that the section to which one is linking will contain the desired content (or even exist). It's thus important that we provide complete, accurate, and (ideally) consistent tags for the various versions of the spec.

Our tags are a mess. We're now using [xyz][1] for releases (#191) so we won't use an inconsistent tag name or forget to tag a release commit in future, but we should make the tagging of older versions as consistent as possible without breaking anything.

Current state:

| Version       | Commit                                                                                                    | Tag name      | Tag type          |
|:-------------:| --------------------------------------------------------------------------------------------------------- | ------------- | ----------------- |
| __v0.1.0__    | [`7fc1a62`](https://github.com/fantasyland/fantasy-land/commit/7fc1a62b3c87b6df4f8dd50ae49cedcc64fa29bf)  | `v0.1.0`      | lightweight (!)   |
| __v0.2.0__    | [`900f841`](https://github.com/fantasyland/fantasy-land/commit/900f84178d618977847c00421e1a915a384e7b45)  |               |                   |
| __v0.2.1__    | [`2243ee9`](https://github.com/fantasyland/fantasy-land/commit/2243ee93fb4e516db8e0050649305034bd1da102)  | `v0.2.1`      | lightweight (!)   |
| __v0.3.0__    | [`d119757`](https://github.com/fantasyland/fantasy-land/commit/d119757cca5db2dc3bf83ea56f24fc82c7e11fb4)  |               |                   |
| __v1.0.0__    | [`c6bc53c`](https://github.com/fantasyland/fantasy-land/commit/c6bc53c5eca5cb2fa5384205ae783faf8530e6c0)  | `1.0.0` (!)   | lightweight (!)   |
| __v1.0.1__    | [`04b91c3`](https://github.com/fantasyland/fantasy-land/commit/04b91c37ec6d6307274f78c5737c0bc773c8e943)  | `1.0.1` (!)   | lightweight (!)   |
| __v2.0.0__    | [`5bab744`](https://github.com/fantasyland/fantasy-land/commit/5bab744a5616043a7308f32d0394395cb4dff9dc)  | `v2.0.0`      | annotated         |
| __v2.1.0__    | [`7a1a2d7`](https://github.com/fantasyland/fantasy-land/commit/7a1a2d7d580498a18f80eb11f292e6001da6b67e)  | `v2.1.0`      | annotated         |
| __v2.2.0__    | [`e0088f1`](https://github.com/fantasyland/fantasy-land/commit/e0088f1cb08c01dccb72e3b3e4ebee9c4c22e402)  | `v2.2.0`      | annotated         |

Desired state:

| Version       | Commit                                                                                                    | Tag name      | Tag type          |
|:-------------:| --------------------------------------------------------------------------------------------------------- | ------------- | ----------------- |
| __v0.1.0__    | [`7fc1a62`](https://github.com/fantasyland/fantasy-land/commit/7fc1a62b3c87b6df4f8dd50ae49cedcc64fa29bf)  | `v0.1.0`      | annotated         |
| __v0.2.0__    | [`900f841`](https://github.com/fantasyland/fantasy-land/commit/900f84178d618977847c00421e1a915a384e7b45)  | `v0.2.0`      | annotated         |
| __v0.2.1__    | [`2243ee9`](https://github.com/fantasyland/fantasy-land/commit/2243ee93fb4e516db8e0050649305034bd1da102)  | `v0.2.1`      | annotated         |
| __v0.3.0__    | [`d119757`](https://github.com/fantasyland/fantasy-land/commit/d119757cca5db2dc3bf83ea56f24fc82c7e11fb4)  | `v0.3.0`      | annotated         |
| __v1.0.0__    | [`c6bc53c`](https://github.com/fantasyland/fantasy-land/commit/c6bc53c5eca5cb2fa5384205ae783faf8530e6c0)  | `v1.0.0`      | annotated         |
| __v1.0.1__    | [`04b91c3`](https://github.com/fantasyland/fantasy-land/commit/04b91c37ec6d6307274f78c5737c0bc773c8e943)  | `v1.0.1`      | annotated         |
| __v2.0.0__    | [`5bab744`](https://github.com/fantasyland/fantasy-land/commit/5bab744a5616043a7308f32d0394395cb4dff9dc)  | `v2.0.0`      | annotated         |
| __v2.1.0__    | [`7a1a2d7`](https://github.com/fantasyland/fantasy-land/commit/7a1a2d7d580498a18f80eb11f292e6001da6b67e)  | `v2.1.0`      | annotated         |
| __v2.2.0__    | [`e0088f1`](https://github.com/fantasyland/fantasy-land/commit/e0088f1cb08c01dccb72e3b3e4ebee9c4c22e402)  | `v2.2.0`      | annotated         |

I will create annotated tags for __v0.1.0__, __v0.2.0__, __v0.2.1__, __v0.3.0__, __v1.0.0__, and __v1.0.1__. The existing `v0.1.0` and `v0.2.1` lightweight tags will be replaced by annotated tags. I'll keep the existing `1.0.0` and `1.0.1` lightweight tags around to avoid breaking links. This will mean that each of these versions will have both an annotated tag and a lightweight tag, which is fine.

[1]: https://github.com/davidchambers/xyz

**Comment by davidchambers** [comment]
I've done this. The only thing that's now a little confusing is that Version 1.0.1 appears to be the most recent [release][1].


[1]: https://github.com/fantasyland/fantasy-land/releases

**Comment by safareli** [comment]
@davidchambers this might help i think
http://stackoverflow.com/questions/21738647/change-date-of-git-tag-or-github-release-based-on-it

**Comment by davidchambers** [comment]
We could have done something like that, @safareli, but I think each annotated tag should accurately reflect its creator and creation date and time. Git > GitHub, in other words. If GitHub provided a way to reorder releases without touching Git metadata I would do so.

Once we publish v2.3.0 or v3.0.0 the first release listed will once again be the most recent one.
