### ISSUE TITLE
Connection with FantasyLand Institute?

### ISSUE THREAD

**Issue by EvanBurchard** [fantasyland/fantasy-land#227]
Just wondering if this project is at all connected with the [fantasyland institute](http://fantasyland.institute/). 

If so, please let me know so that I can remove all references to it from my book before it goes to print. 

Thanks.

**Comment by puffnfresh** [comment]
I have worked for two companies run by the person behind that. I was employed by the person at the time this Fantasy Land was created. That is the only connection.
