### ISSUE TITLE
Applicative Spec error?

### ISSUE THREAD

**Issue by ferborva** [fantasyland/fantasy-land#228]
Evening,

Going through the Applicative spec docs I've seen something I'm not quite sure of:

Docs:
Applicative
...
2. **A.of(x).ap(A.of(f)) is equivalent to A.of(f(x))** (homomorphism)
...

I would have expected the homomorphism law to be:

A.of(**f**).ap(A.of(**x**)) is equivalent to A.of(f(x))

Am I write to think there is a typo here or both are true??

**Comment by safareli** [comment]
no it's correct, as`ap` order has changed in [v1](https://github.com/fantasyland/fantasy-land/releases/tag/v1.0.0) #145
