### ISSUE TITLE
Add spec for Ord

### ISSUE THREAD

**Issue by gabejohnson** [fantasyland/fantasy-land#233]
Motivated by https://github.com/sanctuary-js/sanctuary/issues/353 I think it makes sense to add `Ord`.

From [purescript-prelude](https://github.com/purescript/purescript-prelude/blob/b9c91d009fc035d142d3bbb8af52c55681b7b3db/src/Data/Ord.purs#L25-L34)

```purescript
-- | The `Ord` type class represents types which support comparisons with a
-- | _total order_.
-- |
-- | `Ord` instances should satisfy the laws of total orderings:
-- |
-- | - Reflexivity: `a <= a`
-- | - Antisymmetry: if `a <= b` and `b <= a` then `a = b`
-- | - Transitivity: if `a <= b` and `b <= c` then `a <= c`
class Eq a <= Ord a where
  compare :: a -> a -> Ordering
```

This _may_ require specifying `Ordering` as well (though I haven't seen much movement on spec'ing data types #185):

From [purescript-prelude](https://github.com/purescript/purescript-prelude/blob/b9c91d009fc035d142d3bbb8af52c55681b7b3db/src/Data/Ordering.purs#L7-L13)
```purescript
-- | The `Ordering` data type represents the three possible outcomes of
-- | comparing two values:
-- |
-- | `LT` - The first value is _less than_ the second.
-- | `GT` - The first value is _greater than_ the second.
-- | `EQ` - The first value is _equal to_ the second.
data Ordering = LT | GT | EQ
```

Specifying `Ord` would allow generalizing several comparison (`lt` and friends, `min` & `max`) as well as sorting functions (`sort`, `sortBy`).

**Comment by davidchambers** [comment]
To avoid specifying `Ordering` we could use `Number` (though I'd prefer to limit the values to `-1`, `0`, and `1`).

**Comment by gabejohnson** [comment]
@davidchambers that would allow us to state the laws without referencing functions not defined in the spec. Though, by limiting the allowable values of `Number` you are still specifying. You're just not giving a name to the specification.

**Comment by gabejohnson** [comment]
We could just punt by adding a pointer to the 262 [spec](http://ecma-international.org/ecma-262/6.0/#sec-sortcompare).

**Comment by gcanti** [comment]
FYI in fp-ts I'm using `Ordering` and `Ord` borrowed from PureScript

- [Ordering](https://github.com/gcanti/fp-ts/blob/master/src/Ordering.ts)
- [Ord](https://github.com/gcanti/fp-ts/blob/master/src/Ord.ts)
