### ISSUE TITLE
[Feature Request]: Add short explanation to different operators mean. 

### ISSUE THREAD

**Issue by TheLarkInn** [fantasyland/fantasy-land#236]
Hi there, first time I've laid eyes on this beautiful wealth of functional knowledge. However, one thing that is confusing to me is understanding the difference between `=>`, `->`, and `~>`. I think it would be really nice addition to have a short explanation somewhere in the README. I'd probably understand a bit more about all the different functors if so :joy:. 

PS: Am happy to submit the PR if given a bit of guidance.

**Comment by rjmk** [comment]
I believe #223 will fix this you for you. Does that look right to you?

**Comment by TheLarkInn** [comment]
That is perfect!!! Thanks for this (and sorry I didn't notice the PR)
