### ISSUE TITLE
Apply strictness

### ISSUE THREAD

**Issue by ulfryk** [fantasyland/fantasy-land#246]
Apply docs state:

---
A value which has an Apply must provide an `ap` method. The `ap`
method takes one argument:

    a.ap(b)

1. `b` must be an Apply of a function,

---

shouldn't there be requirement that _`b` must be same Apply as `a`_ ?

**Comment by gabejohnson** [comment]
There should also be a fourth clause stating:

`ap` must return a value in the same Apply as `a` and `b`

Or something to that effect.

**Comment by ulfryk** [comment]
Would you like me to file a PR ?

**Comment by safareli** [comment]
> Would you like me to file a PR ?

Yes

**Comment by ulfryk** [comment]
@gabejohnson  @safareli -> #247
