### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by char0n** [fantasyland/fantasy-land#251]
I am a big fan of fantasy-land. Today I come across an issue when trying to use fantasy-land laws to test my reference implementation of Identity type. My tests run under node 4, 5, 6, 7. The codebase of fantasy-land will run only for node of version => 6.  When I want to use the laws on node 4 or 5 I got syntax error due to the fact that there are places where  object destructuring are used. And destructuring is only supported on node => 6.

I propose to create a prepublishOnly entry in package.json, and use babel to transpile the sourcecode into valid ES5 code. That way even older nodes can benefit from fantasy-land. Before publising to npm, ES5 tranpiled version of code will be created in ./lib directory and 'main' entry in package.json will point to this dir. Take a look [here](https://github.com/char0n/ramda-adjunct/blob/09cd751bb832e787f6e4bea3c2ddaa3b4554093d/package.json#L65) what I have in mind.

I can create a PR with all described above, I just need a green light to do so.

Thank you

**Comment by safareli** [comment]
@davidchambers is this issue solved with https://github.com/fantasyland/fantasy-laws/pull/1 ?

**Comment by davidchambers** [comment]
We're currently using `=>` syntax in fantasyland/fantasy-laws#1, but we can easily switch back to ES5-compatible syntax.

@char0n, would you mind opening an issue for this in [fantasyland/fantasy-laws][1]?


[1]: https://github.com/fantasyland/fantasy-laws

**Comment by char0n** [comment]
@davidchambers copypasted the issue to fantasyland/fantasy-laws. Do you want me to provide a PR there ?

**Comment by davidchambers** [comment]
> Do you want me to provide a PR there ?

Don't worry. I've added an item to the to-do list in fantasyland/fantasy-laws#1. I'll close this issue since we're now tracking it elsewhere. :)
