### ISSUE TITLE
Add a license & contributing guidelines

### ISSUE THREAD

**Issue by kennknowles** [fantasyland/fantasy-land#26]
It should be clear what license the documentation and test suite are under, and perhaps a `CONTRIBUTING` file that makes clear that pull requests are implicit license. This latter is a bit litigious but I've seen it around sometimes.

**Comment by necolas** [comment]
Any update on this?

**Comment by puffnfresh** [comment]
@necolas I added a plain MIT license to master.

**Comment by necolas** [comment]
Thanks!

**Comment by SimonRichardson** [comment]
Closing, if you want to suggest a `CONTRIBUTING` please reopen and we can move things forward. I think the MIT license is sufficient for now.
