### ISSUE TITLE
`daggy` and `fantasy-combinators` unused dependencies

### ISSUE THREAD

**Issue by xgbuils** [fantasyland/fantasy-land#264]
Hi!

`daggy` and `fantasy-combinators` are defined as dependencies in `package.json` but the main file `index.js` doesn't require them.

Could they be removed or are they dev dependencies?

**Comment by davidchambers** [comment]
These dependencies are required by `fantasy-land/laws`. We'll be able to remove that directory and these dependencies once fantasyland/fantasy-laws#1 is merged. :)
