### ISSUE TITLE
"any" vs. "all" in docs

### ISSUE THREAD

**Issue by dakom** [fantasyland/fantasy-land#267]
The README states this in the fat-arrow section:

> To satisfy a typeclass means to implement any function/method defined by that typeclass.

Is this correct? should it not be "implement all functions/methods defined by that typeclass"?

(I'm new to this stuff and might be totally off, if so, I'd love it even better to learn about the difference between typeclasses and interfaces! :D)

**Comment by davidchambers** [comment]
You're right, @dakom. Please submit a pull request to change _any_ to _all_ if you feel so inclined. :)

**Comment by dakom** [comment]
Here it is: https://github.com/fantasyland/fantasy-land/pull/268
thanks!

**Comment by davidchambers** [comment]
Thanks for the pull request, David. :)
