### ISSUE TITLE
How to understand these common algebraic structures?

### ISSUE THREAD

**Issue by wenkanglin** [fantasyland/fantasy-land#277]
![image](https://user-images.githubusercontent.com/21100124/32872012-4f78e5ca-cabf-11e7-8336-6f18a1de180a.png)

Is there any way I can understand these common algebraic structures in the above picture?

I'm a javascript developer, but in terms of functional programming, I'm a rookie. I'm interested in functional programming and tooke some time to understand the concept of `Curried`, `Pure Function`, `Compose`... But I don't quite understand  what `Functor`, `Monad`, `Chain`, `Applicative` are :sweat:

Is there any website or other ways to help me understand these concepts?

**Comment by safareli** [comment]
This concepts are from Haskell/PureScript, so any beginner resource related to that languages will help. for example:
- Books: Learn you a Haskell
- Books:  PureScript, by example
- Books: The Haskell book

If you want to go deep into category theory you could take a look at this:
- https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/
- https://www.youtube.com/watch?v=I8LbkfSSR58&list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_


Also when i was getting started with FP, I have collected some resources here https://github.com/safareli/fp-stuff

**Comment by wenkanglin** [comment]
@safareli Thx! I decided to learn Haskell language to understand purely functional programming :smile:

**Comment by gabejohnson** [comment]
@wenkanglin, there's also a really good blog series   http://www.tomharding.me/2017/03/03/fantas-eel-and-specification/ which covers most of the algebras in the spec.

**Comment by wenkanglin** [comment]
@gabejohnson :ok_hand:
