### ISSUE TITLE
Question about function type constructor explain

### ISSUE THREAD

**Issue by neighborhood999** [fantasyland/fantasy-land#279]
In `Function type constructor` second explain：

> The syntax is: (<input-types>) -> <output-type>, where <input-types> comprises zero or more comma–space (,)-separated type representations and parens may be omitted for unary functions.

Sorry, I'm not a native in English so I feel confuse, Is **parens** means **parents**? Thanks!

**Comment by davidchambers** [comment]
Thank you for raising this issue, @neighborhood999. I'm sorry that the wording is unclear. _Parens_ is another way of writing _parentheses_, the plural form of _[parenthesis][1]_.

The quoted sentence states that although one could write `(a) -> b`, for a function with exactly one parameter it's okay to write `a -> b` instead (without parens).

I hope this is clearer now. :)


[1]: http://www.wordnik.com/words/parenthesis
