### ISSUE TITLE
Confused about `ap`

### ISSUE THREAD

**Issue by babakness** [fantasyland/fantasy-land#283]
This article seems to indicate that the function in Container supplying `ap` applies its *function* to the value contained in the functor pass into `ap` as a parameter

https://drboolean.gitbooks.io/mostly-adequate-guide-old/content/ch10.html#ships-in-bottles

This article confirms the same idea

https://github.com/hemanth/functional-programming-jargon#applicative-functor

Yet this article seems to imply the reverse, basically `ap` is `map`

https://github.com/fantasyland/fantasy-land#apply

A value which has an Apply must provide an `ap` method. The `ap`
method takes one argument:

    a.ap(b)

> 
> 1. `b` must be an Apply of a function
> 
>     1. If `b` does not represent a function, the behaviour of `ap` is
>        unspecified.
>     2. `b` must be same Apply as `a`.
> 
> 2. `a` must be an Apply of any value
> 
> 3. `ap` must apply the function in Apply `b` to the value in
>    Apply `a`
> 
>    1. No parts of return value of that function should be checked.
> 
> 4. The `Apply` returned by `ap` must be the same as `a` and `b`

3 states that `b` is a function applied to a.

Suppose we have some Box defined as

```javascript
const Box = x => ({
  map: f => Box(f(x)),
  ap: f => f.map(x),
  inspect: () => `Box(${x})`,
})

const a = x => x + 1
const b = 4
console.log(
  Box( a ).ap( Box( b ) ).inspect() === Box( b ).map( a ).inspect()
)
// true
```

Is this Box implementing `ap` correctly (per these specs)?

**Comment by paldepind** [comment]
The argument order for `ap` was changed some time ago. What was previously `a.ap(b)` is now `b.ap(a)`. If you want to lift a function of three arguments over three applicatives with the new API you do:

```js
c.ap(b.ap(a.map(f)));
```

Instead of the old `a.map(f).ap(b).ap(c)` that is shown in your link.

> Yet this article seems to imply the reverse, basically `ap` is `map`

`ap` is not `map`. `map` takes a "plain" function as it's argument whereas `ap` takes an applicative of a function as its argument. If `A` is an applicative then this is types for `map` and `ap`.

```ts
map<A>(f: (a: B) => C): A<C>
ap<A>(af: A<(a: B) => C>): A<C>
```

> Is this Box implementing `ap` correctly (per these specs)?

Yes, it looks that way to me.

**Comment by Avaq** [comment]
I'd like to extend on @paldepind his answer, and go a little more in depth.

> The argument order for `ap` was changed some time ago. -- @paldepind 

The argument order for `ap` changed between Fantasy Land 0.x and 1.0. At the same time, the Fantasy Land spec also changed from specifying a *public* API, to specifying a "private" API. Namely, all methods were prefixed by `fantasy-land/`. The Fantasy Land methods are not to be used directly.

Providing a user-facing, public, method-based API is completely up to the author of a library. The only reason you would implement the `fantasy-land/`-prefixed methods is to provide a communication layer for interoperability.

Some libraries do not expose a public method API at all. For example, [Sanctuary](https://sanctuary.js.org/) and its algebraic types.

Some libraries expose a public method API where the argument order benefits "fluent method chaining" style. For example, [`Fluture#ap`](https://github.com/fluture-js/Fluture#ap) has the function on the left-hand side (the instance). Fluture also implements `fantasy-land/ap`, with flipped argument order.

In the Mostly Adequate Guide, *only* a public API is implemented, none of which is compatible with Fantasy Land (the confusing bit is that it *used to be*). Now, Fantasy Land compliance is merely an interoperability layer that can added to constructors, to indicate to other code that their values have algebraic properties.

> over three applicatives with the new API you do `c.ap(b.ap(a.map(f)))` -- @paldepind 

Just to stress my point. With the new API you do:

```js
c['fantasy-land/ap'](b['fantasy-land/ap'](a['fantasy-land/map'](f)))
```

Which as a user, you don't. The new "API" is not for public use.

> Is this Box implementing `ap` correctly (per these specs)? -- @babakness 

* Correctly: **yes**. The algebraic properties hold.
* Conveniently: **no**. It's a method API that doesn't facility the common case very well.
* As per the spec: **no**. The method name is missing its `fantasy-land/` prefix.

**Comment by alexeyraspopov** [comment]
> Is this Box implementing ap correctly (per these specs)?

> Correctly: yes. The algebraic properties hold.

I found this a bit confusing. The example shows basically:

```
a = Apply of a function x => x + 1
b = Apply of a value 4

a.ap(b)
```

However, [Apply spec](https://github.com/fantasyland/fantasy-land#apply) requires `b` to be Apply of function. Am I missing something?

**Comment by Avaq** [comment]
> The algebraic properties hold.

...within the closed system where this type is present (the Mostly Adequate Guide).

> [The Fantasy Land] Apply spec requires `b` to be Apply of function. Am I missing something?

Let's look at what Fantasy Land *is* exactly:

> Specification for **interoperability of** common algebraic structures in JavaScript

So Fantasy Land does not necessarily specify what it means to have these algebraic properties. Instead, Fantasy Land specifies *how to arrange methods on objects in JavaScript* such that the algebraic properties intrinsic to the type can be understood and used by third parties. It just happens to be that a lot of the algebraic properties also have to be specified if your goal is interoperability.

<sup>I'm not a spokesperson of Fantasy Land, and to be sure my views are valid I'll ping @puffnfresh to give him the opportunity to correct me.</sup>

**Comment by zhirzh** [comment]
@paldepind [you say](https://github.com/fantasyland/fantasy-land/issues/283#issuecomment-362183754) that the argument order for `ap` was changed and is now `b.ap(a)` but it's still the same in the [`Apply section`](https://github.com/fantasyland/fantasy-land#apply).

Update?
