### ISSUE TITLE
Why is the class/constructor required as a parameter for `traverse` (or sequence)?

### ISSUE THREAD

**Issue by babakness** [fantasyland/fantasy-land#297]
A `Fantasy-land` compliant version of `traverse` might go something like this:

```js
S.traverse (Array) (S.words) (S.Just ('foo bar baz'))
``` 

But why are we asking for the first `(Array)` parameter? If the words function must return an Array, could we not access the constructor of the Array as such:

```js
const foo  = [1,2,3]
const foo2 = foo.constructor.of( 4,5,6 )
```
So why do we need `Array` at all? Here `S.words` returns an `Array` Monad contained within the `Maybe`. We can then derive the `Array` constructor as mentioned above to `sequence` an `Array` of `Maybe`s.

**Comment by evilsoft** [comment]
From my understanding, I has to do with when you have say `[ Maybe String ]`, but the data you get passed to you is an empty `Array`, you do not know how to construct a `Maybe` as there is no instance to get the `Maybe` from.

Same for like a `Maybe [ String ]`...if you receive a `Nothing`, you cannot construct the `Array` as there is no instance.

Even in a case like `Either String [ Number ]`, you you ever get a `Left` that would be a `String` instance. In an adhoc language like JS, we can not infer the inner type from just a siggy.

**Comment by davidchambers** [comment]
@evilsoft is spot on. :)

**Comment by babakness** [comment]
I'm just experimenting with it right now and it works

```ts
export type Maybe<A> = Nothing<A> | Just<A>
export const Maybe = {
  // ..
  of: <A>(a: A): Maybe<A> => {
    return isNully(a) ?  nothing : Just.of(a) 
  },
}

class Nothing {
  // ...
  sequence<F extends URIS,B,C>( ) : any {
    return nothing 
  }
  traverse<F extends URIS,B,C>( this: Maybe<A> , fn: (a: A) => (HKT<F,B> & Apply<B>) | (HKT<F,B> & ArrayApply<B>)): Type<F,Maybe<B>> {
    return nothing
  }  
}

class Just { 
  // ...
  traverse<F extends URIS,B,C>( this: Maybe<A> , fn: (a: A) => (HKT<F,B> & Apply<B>) | (HKT<F,B> & ArrayApply<B>)): Type<F,Maybe<B>> {
    const functor = this.isJust() ? fn(this.value) : nothing
    return Maybe.of(functor).sequence()
  }  
  
  sequence<F extends URIS,B,C>( this: Maybe<HKT<F,A> & Apply<A>> ): any {
    const functor = this.isJust() ? this.value : nothing
    const isArray = (f):f is HKT<F, B> & ArrayApply<B> => Array.isArray(f) 
    return ( isArray(functor) ? functor[adtn.ap] : functor.ap )
      .call( functor, (functor.constructor as any).of( Maybe.of ) )
  }
}
```

```ts

test('sequence', t => {
  t.deepEqual(
     Maybe.of( 'it works' ).traverse( str => str.split(' ') ),
     [ Just.of('it'), Just.of('works')]
}) // passes
```

Am I misunderstanding the problem?

**Comment by evilsoft** [comment]
What happens with `Nothing`?

**Comment by babakness** [comment]
Ah, right ok, you get `Nothing` not `[ Nothing ]`

**Comment by babakness** [comment]
If you have `Nothing` `traverse` is not executed at all. So even passing `Array` as a parameter does nothing. I suppose `traverse` must be an external function operating on the Applicative and not a method on the Applicative fo this reason.

**Comment by evilsoft** [comment]
Pardon the silly pattern, but this is one way that I have implemented traverse on a `Maybe` type:
https://github.com/evilsoft/crocks/blob/master/src/core/Maybe.js#L210

The left side of that `either` function is for the `Nothing` case, so it composes a `Nothing` constructor before the `af` or `Applicative` function resulting in the `Applicative m => m Maybe a`

**Comment by babakness** [comment]
@evilsoft Hey! Didn't see your message before deleting the comment, I realized that of course `Nothing` can implement a `traverse` that wraps a `Nothing` into the desired Applicative.

Thanks for the reference, I like your library--its pretty awesome. I dig the runtime checks :-)
