### ISSUE TITLE
Wrong argument in Traversable

### ISSUE THREAD

**Issue by Ne4to777** [fantasyland/fantasy-land#318]
Definition:
fantasy-land/traverse :: Applicative f, Traversable t => t a ~> (TypeRep f, a -> f b) -> f (t b)
Rule:
t(u['fantasy-land/traverse'](F, x => x)) is equivalent to u['fantasy-land/traverse'](G, t) for any t such that t(a)['fantasy-land/map'](f) is equivalent to t(a['fantasy-land/map'](f)) (naturality)
Issue:
definition part (a -> f b) is not equal to rule part (x => x)

**Comment by davidchambers** [comment]
@Ne4to777, are you saying that `x => x` cannot be a member of `a -> f b`? What if we were to make the following substitutions?

```haskell
-- replace ‘a’ with ‘Array Number’
Array Number -> f b

-- replace ‘f’ with ‘Array’
Array Number -> Array b

-- replace ‘b’ with ‘Number’
Array Number -> Array Number
```

**Comment by Ne4to777** [comment]
You are right. Tanks.

**Comment by davidchambers** [comment]
No problem. :)

**Comment by rpominov** [comment]
Even more common case when `x => x` is valid is when you already have applicatives inside your traversable. In other words your `a` happen to be `f b`.
