### ISSUE TITLE
Is monet.js compatible?

### ISSUE THREAD

**Issue by MartinMuzatko** [fantasyland/fantasy-land#319]
I've not seen [monet](https://monet.github.io/monet.js/) listed in https://github.com/fantasyland/fantasy-land/blob/master/implementations.md

But I'd like to have fantasy-land spec compatible libs for my node JS app.
Since I am fairly new, I'd love to have your input on this.
Thank you in advance

**Comment by davidchambers** [comment]
This suggests compatibility: <https://github.com/monet/monet.js/search?q=fantasy-land>.
