### ISSUE TITLE
What does "and" mean?

### ISSUE THREAD

**Issue by fxkr** [fantasyland/fantasy-land#322]
From README.md:

![image](https://user-images.githubusercontent.com/389616/82409024-b1742a80-9a21-11ea-85de-e350c5ab6134.png)

Which of the following two interpretations is the right hand side of above statement referring to?

* (`42` is a member of type `Integer`) and (`42` is a member of type `Number`)
* `42` is a member of the type (`Integer` and `Number`)

Where (`Integer` and `Number`) would be some kind of union type, constructed from the types `Integer` and `Number` using the `and` operator, or something? The `and` operator hasn't been introduced, so I am leaning towards taking first interpretation, but it says "type" (singular not plural), and also `and` is monospaced which both hints at the second interpretation.

**Comment by Avaq** [comment]
It means that 42 is a member of type Integer, as well as a member of type Number. So a member of two types.

---

If we would want to create an IntegerNumber type whose members are all values that are members of Integer as well as Number, then the operator to use would be [intersection (∩)](https://en.wikipedia.org/wiki/Intersection_(set_theory)). So we could also say: *42 is a member of type Integer ∩ Number*. And that would also be true, but that's not what we're trying to convey. If a type "Integer ∩ Number" would exists, then 42 would be a member of Integer, Number, *and* Integer ∩ Number. So we're trying to make the reader aware of the full list of known types that a value is a member of.

**Comment by davidchambers** [comment]
Shall we update the wording to _`42` is a member of the `Integer` and `Number` types_?
