### ISSUE TITLE
Can someone explain me how I should understand Semigroup?

### ISSUE THREAD

**Issue by Munkyu-Yang** [fantasyland/fantasy-land#325]
```js
fantasy-land/concat :: Semigroup a => a ~> a -> a
```

Since there are so many `a`s, it's quite confusing though I've read the documentation.
Can someone provide me an actual example please?

**Comment by davidchambers** [comment]
Here are some examples, using [`S.concat`][1]:

```javascript
> S.concat ('abc') ('def')
'abcdef'

> S.concat ([1, 2, 3]) ([4, 5, 6])
[1, 2, 3, 4, 5, 6]

> S.concat ({x: 1, y: 2}) ({y: 3, z: 4})
{x: 1, y: 3, z: 4}

> S.concat (S.Just ([1, 2, 3])) (S.Just ([4, 5, 6]))
Just ([1, 2, 3, 4, 5, 6])

> S.concat (Sum (18)) (Sum (24))
Sum (42)
```

`S.concat` is easier to understand than the underlying `fantasy-land/concat` methods for several reasons:

  - its type signature does not contain a squiggly arrow (`~>`);
  - it does not reference `fantasy-land/concat` explicitly; and
  - it works for some built-in types such as `String`, even though `String.prototype['fantasy-land/concat']` is undefined.

Here is an example of invoking a `fantasy-land/concat` method directly:

```javascript
> S.Just ('abc') ['fantasy-land/concat'] ('def')
Just ('abcdef')
```


[1]: https://sanctuary.js.org/#concat

**Comment by CrossEye** [comment]
As well ad David's excellent answer, [Tom Harding's series][fe] on these FantasyLand types is excellent.  [Semigroups][se] is the fourth entry.

  [fe]: http://www.tomharding.me/fantasy-land/
  [se]: http://www.tomharding.me/2017/03/13/fantas-eel-and-specification-4/

**Comment by alexr007** [comment]
Just a Monoid without zero value.
Operation only.

**Comment by juboba** [comment]
> ```js
> fantasy-land/concat :: Semigroup a => a ~> a -> a
> ```
> 
> Since there are so many `a`s, it's quite confusing though I've read the documentation.
> Can someone provide me an actual example please?

If you want to understand the type signature, reading from left to right:

- `Semigroup a =>` means: "The `a` that you will see from now on has a Semigroup"
- `a ~>` means: The following function is a method of an `a` (chain is a method of an instance that has a Semigroup)
- `a -> a` means: it's a function that receives an `a` and returns something of the same type `a`

In David's last example the first `S.Just ('abc')` is the `a` before the `~>`.

**Comment by CrossEye** [comment]
@jujoba: There's a typo in the second bullet.

> -  `a ~>` means: The following function is a method of an a (chain is a method of an instance that has a Semigroup)

should read

> -  `a ~>` means: The following function is a method of an a (**concat** is a method of an instance that has a Semigroup)
