### ISSUE TITLE
Implementation of `Compose` is confusing

### ISSUE THREAD

**Issue by somebody1234** [fantasyland/fantasy-land#332]
I'm wondering how the implementation of `Compose` works?
Assuming `f` is `Compose (a -> b)` then `f.c` must be `a -> b`. However, that would mean `f.c['fantasy-land/map']` is undefined (unless `Functor` is implemented for functions)?

Am I just misunderstanding something here, or...?

**Comment by gabejohnson** [comment]
`Function`s in JavaScript have a type `Function (a | null | undefined) (b | null | undefined)`, but lets say `Function a b` for simplicity's sake. While `Function a b` doesn't have a `Functor` instance, `Function SomeType b` does. It can be defined as follows:
```javascript
Function.prototype['fantasy-land/map'] = function (f) {
  var g = this;
  return function (a) {
    return f(g(a));
  };
};

// usage
// `Function Number Number` composed with `Function Object String` => `Function Number String` or `(Number -> String)`
(x => x + 1)['fantasy-land/map'](x => x.toString())(42); // '43'
```

As evidenced by the result, you can see that `Function.prototype['fantasy-land/map']` is equivalent to `Function.prototype['fantasy-land/compose']`.

**Comment by somebody1234** [comment]
Ah... makes sense I guess, but not sure whether that's clear in that impl... surely it'd be clearer to just write it as normal composition rather than `[map]`?
