### ISSUE TITLE
Decouple Monad from Applicative

### ISSUE THREAD

**Issue by raimohanska** [fantasyland/fantasy-land#42]
I'm afraid it's not always correct to assume that a Monad is also an Applicative. At least I tried to implement the specs into Bacon.js today, for an excersise, and run into issues because of this assumption. I'm not sure how familiar you're with Bacon.js, but I'll try to explain the case anyway.

Now an EventStream in Bacon.js is clearly a Monadic structure: the `flatMap` method (aliased now as `chain`) of EventStream has one parameter which is a function that creates a new EventStream for each value in the original stream. In combination with `EventStream.of` we have a nice Monad. Except.

The Applicative interface for EventStreams doesn't make much sense, at least if based on flatMap: the result stream `a.ap(b)` would take apply each function from the source stream to all (or one?) *subsequent* elements in the stream b. It would make more sense to base `ap` on `combine` or even `zip`, but I'd rather not have EventStream implement Applicative because of this ambiguity. 

In Haskell, you can declare Monad without Applicative. Why not in Fantasy Land?

The fantasy-land version of Bacon.js is in the [fantasy-land](https://github.com/raimohanska/bacon.js/tree/fantasy-land) branch. I'm planning to bring that to master, if I can come up with a nice solution. The current EventStream/Applicative one seems to be compliant, but I would never use it because Applicative through flatMap just makes no sense.

I'd like to have EventStream implement Functor and Monad (no Applicative), and Property implement Functor and Applicative (and a Duck Monad (Property.flatMap returns an instance of EventStream)).

Please ask for more details if this made no sense to you :)

**Comment by SimonRichardson** [comment]
I'm closing this one, reopen if you wish to suggest other wise.
