### ISSUE TITLE
Question about Applicatives

### ISSUE THREAD

**Issue by cwmyers** [fantasyland/fantasy-land#50]
Hi guys,

I've been implementing FantasyLand in monet.js and I've come a little unstuck with `ap()`.

Unless I've got the wrong end of the stick FantasyLand's `ap()` demands that the applicative already contains a function and then accepts an applicative with a value.  

`appWithFunction.ap(appWithValue)`

Unfortunately I've followed scalaz & functional java approach which does the opposite.  

`appWithValue.ap(appWithFunction)`

See here for the `Maybe` example: http://cwmyers.github.io/monet.js/#apmaybefn

Here is an example from FunctionalJava `Option`:
`public final <B> Option<B> apply(Option<F<A,B>> of)` 

So my question is why has Fantasy Land taken this particular approach to applicative?  I'm worried that this would be a large breaking change to the monet library and I'm trying to figure out what the right thing is to do.

Cheers,
Chris

**Comment by SimonRichardson** [comment]
Should we flip the order of `ap`, or just live with it?

**Comment by rpominov** [comment]
I'm having trouble typing `ap()` with Flow, ended up with this:

```js
  // Apply
  ap<A,B>( other:Stream<A> ): Stream<B> {
    // In order for .ap() to work `this` must be a `Stream<A => B>`,
    // but I don't know how to express that constraint in Flow, so just use `any`
    const streamF:BasicStream<any> = this.observe
    return new Stream(bs.ap(streamF)(other.observe))
  }
```

Would be straightforward if it was other way around.

**Comment by joneshf** [comment]
That is quite unfortunate. Can you actually write the other way with flow?

**Comment by rpominov** [comment]
Sure, with reversed version of ap it will look like this:

```js
class Stream<T> {

  ap<A>( other:Stream<( x:T ) => A> ): Stream<A> {
    return new Stream(bs.ap(other.observe)(this.observe))
  }

}
```

**Comment by rpominov** [comment]
For the record: not a big problem for me, just wanted to add my two cents :)

**Comment by SimonRichardson** [comment]
I've been hit with this recently as well. So the question is how do we change it, because I think we should!

Could we maybe rename `ap` to something else, or do we say if you depend on the new fantasy-land #92 `ap` works like this now?

**Comment by rpominov** [comment]
We could certainly use NPM to help us manage changes like that after libraries start depending on FL.

We could do for example:

 - `1.0` backward compatibility release with unprefixed names and no changes to the spec
 - `2.0` adds prefixes therefore providing clashes safety, but still no changes to the spec
 - `3.0` no changes in method names, but includes changes to spec like this and #88

Then libraries could specify appropriate versions range in their peerDependency to `fantasy-land`, and consumers won't be able to use two incompatible libraries (they want be able to install version of `fantasy-land` that satisfies peerDependency for all of incompatible libs).

**Comment by SimonRichardson** [comment]
I'd rather have 3.0 out before 2.0 :dancer:

**Comment by rpominov** [comment]
No preference on that matter from me :)
We could also squash 3.0 and 2.0 to one version, btw.

**Comment by bergus** [comment]
So you only want to change this because flow's type system is not sophisticatd enough?

**Comment by rpominov** [comment]
Yep, and also the fact that it's inconsistent with `map` and `chain` and was a mistake from the beginning (see https://github.com/fantasyland/fantasy-land/issues/50#issuecomment-27708812)

Feel free to discuss in the [PR](#145)

**Comment by Avaq** [comment]
I think this can be closed now, no?

**Comment by SimonRichardson** [comment]
Indeed it can!

**Comment by char0n** [comment]
Sorry for commenting on closed issue, but It may help somebody dealing with the same issue as I did. I heavily use monet.js algebraic structures along with ramda. As @cwmyers pointed out, applicatives in monet.js are not compatible with fantasy-land spec. Though one cannot use ramda's `liftN` to work with monet's applicates. I implemented `liftFN` to create interop for monet.js and ramda.  It is part of  [ramda-adjunct](https://github.com/char0n/ramda-adjunct) and you can find more information in the [docs](https://char0n.github.io/ramda-adjunct/1.3.0/RA.html#.liftFN).

**Comment by evilsoft** [comment]
@char0n looks like [ramda#1900](https://github.com/ramda/ramda/pull/1900) was merged. So soon, very soon, once ramda releases its next version we should all be gtg!!

**Comment by char0n** [comment]
@evilsoft I've just tried using `lift` from master branch of ramda, but it still doesn't work with monet.js algebraic structures. liftFN from ramda-adjunct still working. I am still investigating  the issue...

I have one additional question regarding composition of Apply spec regarding `v.ap(u.ap(a.map(f => g => x => f(g(x))))) is equivalent to v.ap(u).ap(a) (composition)`

```javascript
const add3 = curry((a, b, c) => a + b + c);

const m10 = Maybe.Some(10);
const m15 = Maybe.Some(15);
const m17 = Maybe.Some(17);

m10.ap(m15.ap(m17.map(add3)))
```

What is the eqvivalent of `v.ap(u).ap(a)` in my real code example ? Is this type of composition still possible when the `ap` argument must by apply of a function ?
