### ISSUE TITLE
Traversable

### ISSUE THREAD

**Issue by joneshf** [fantasyland/fantasy-land#52]
Traversable is pretty neat. What do we say about adding this to the spec? Of course it depends on #7 being approved. Is there standard nomenclature for either `traverse` or `sequence`? Which one are we suggesting in the spec? Or do we allow either, with a derivable implementation for the other?

**Comment by joneshf** [comment]
With #68 being merged, this can be closed yes?

**Comment by DrBoolean** [comment]
Yeah, sucks that we should enforce `of` as a second arg to `traverse` since it's not needed 90% of the time, but nothing else to do.
