### ISSUE TITLE
Why name the Comonad method "from"?

### ISSUE THREAD

**Issue by bergus** [fantasyland/fantasy-land#72]
I did like the name `extract` that was proposed in #57 much more. Why was `from` chosen?

To me (and probably most other people who don't know what comonads are about), `extract` is more descriptive and meaningful. Don't we [want](3) a self-explanatory spec? It matches the [Haskell function](http://hackage.haskell.org/package/comonad-4.2/docs/Control-Comonad.html#v:extract) as well.

Also, I have some reservations against using `from`. The term is used in ES6 for static (constructor) methods to assimilate values in a type, e.g. [`Array.from`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-array.from). Don't we expect some collisions, especially since `from` originally had a static counterpart (7253b836d86ecc434bcd9775255646b8001fec72)?

Sorry for not bringing this up earlier, I seem to have forgotten to watch this repo.

**Comment by 5outh** [comment]
@bergus I named it `from` because `return` was renamed to `of`, and `from` seemed to match that convention slightly better. I think that `extract` is a good name as well and wouldn't mind seeing it renamed. I didn't realize there was an ES6 collision either, good find!

**Comment by SimonRichardson** [comment]
Can we close this one, or create a PR with suggested fixes?

**Comment by bergus** [comment]
@SimonRichardson: Done :-)
I don't have much experience with Github's online edit interface, so I might have done something odd (please hint me).

**Comment by SimonRichardson** [comment]
Closing, as it's been merged.
Congrats!

**Comment by 5outh** [comment]
Thanks @bergus :+1:
