### ISSUE TITLE
Add Quickcheck to spec to motivate dev dependency

### ISSUE THREAD

**Issue by DrBoolean** [fantasyland/fantasy-land#73]
Over at #68 I had an issue with using `Id` to express a traversable law - i.e. using an implementation within the spec.

At #66 @phadej suggested we motivate some reason to depend on the spec so we can chart it's use and have a reason for versioning.

I'd like to see a law quickcheck test script included in the spec. Something like: https://github.com/folktale/laws

That would allow people to add fantasy-land as a dev dependency as well as give me a reason to include `Id`

My vision is something like:
```js
var fl = require('fantasy-land')
fl.quickcheck(MyType, [fl.functor, fl.traversable, fl.foldable]);
```

I also believe it makes sense to do the derivations from `fl`, but that might be overboard.

**Comment by SimonRichardson** [comment]
I've moved the quick check lib to fantasy land. It's not as simple as what you've got in your example, but could easily be added via a wrapper!

https://github.com/fantasyland/fantasy-check

**Comment by SimonRichardson** [comment]
I'm going to close this, as we do have a checking library for it now. You can suggest helper methods (see @DrBoolean idea above) in that library now :)
