### ISSUE TITLE
Add Then (>>) to monad spec

### ISSUE THREAD

**Issue by TrevorBasinger** [fantasyland/fantasy-land#83]
For example:
```
Id.prototype.then = function (m) {
    return m;
}
```

```
Promise.prototype.then = function (m) {
    var promise = this;
    return new Promise (function (resolve) {
        return promise.fork (function (dontCare) {
            return m.fork (resolve);
        });
    });
}
```

Then you could have code like this:
```
somethingToDo (x) // Returns Future
    .chain (thisAlsoReturnsAFuture)
    .then  (justDoFinalFuture)
```

instead of:
```
somethingToDo (x) // Returns Future
    .chain (thisAlsoReturnsAFuture)
    .chain (konst (justDoFinalFuture))
```
Thoughts?

**Comment by 5outh** [comment]
If `then` is the same as `>>`, then:

```js
m.then(k) === m.chain(function () { return k; });
```

It may be worth mentioning that this is the case and that `then` can be useful, but I don't know if `then` should need to be implemented outright or appear as a requirement for any of the structures.

If you can think of a way to incorporate `then` into fantasy-land, go ahead and submit a PR! I'd love to see how it comes out on paper and would be happy to see mention of `>>` in the `chain` specification.

**Comment by bergus** [comment]
`then` has a very specific meaning in promise libraries. Please avoid name clashes with those.
