### ISSUE TITLE
why these identifiers?

### ISSUE THREAD

**Issue by davidchambers** [fantasyland/fantasy-land#86]
What is the reasoning behind the choice of identifiers `u`, `v`, `w`, `x`, and `y` in the specification? I can see why `a`, `b`, `f`, and `m` were chosen in the contexts they're used, but I can't do the same for the letters near the end of the alphabet.

**Comment by puffnfresh** [comment]
No idea :sunglasses:

**Comment by 5outh** [comment]
`w` is mainly used in the comonad spec because that's how it is in [Control.Comonad](https://hackage.haskell.org/package/comonad-0.1.1/docs/Control-Comonad.html) (upside-down `m`, I guess!)

**Comment by SimonRichardson** [comment]
Can we close this one, or create a PR with suggested fixes?

**Comment by davidchambers** [comment]
I'll create a PR.
