### ISSUE TITLE
Create fantasy-land-promise proposal

### ISSUE THREAD

**Issue by Gozala** [fantasyland/fantasy-land#9]
I think promises/a+ is a lost cause. But DOM Futures is probably not. I thin it would be very useful to have spec outlined and proposed to whoever is working on DOM Futures! I think
the goals of the spec should be:

Define `Monad`-ic promises that that is backwards compatible with Promise/A. In other words `then` is de-facto standard and it's too late to change it. But `then` could be defined by complecting `flatMap` and some error handling mechanism (see #8)

**Comment by SimonRichardson** [comment]
Can I close this, it seems like this is a dead end?

**Comment by bergus** [comment]
I don't know whether it's useful to create a fantasy-land-promise specification, but I think we should leave this open, for keeping track of promise implementations that follow the fantasyland spec. I think it's still worth pursuing to get Monad methods in all promise implementations, including ES7. While `then`/`catch` is the standard, there's nothing that prevents us from providing `map`, `chain`, `ap`, `of` as well. Let's put some efforts in making them popular for use with promises!

**Comment by joneshf** [comment]
@bergus we have https://github.com/fantasyland/fantasy-land/blob/master/implementations.md to keep track of conforming implementations.

**Comment by SimonRichardson** [comment]
I agree. @bergus I'm not disagreeing with you, I just want to see issues either move forward or closed. We shouldn't keep issues open for ever, without movement.

**Comment by bergus** [comment]
@joneshf Sure, I meant this issue less to keep track of them but rather to encourage their use :-)
Maybe we could rename it into "*Get FL methods into ES7 promises*"?

What do you think about an own section in implementations.md for promises?
