### ISSUE TITLE
Monad left identity law, is it correct?

### ISSUE THREAD

**Issue by Weitklick** [fantasyland/fantasy-land#93]
Hi, I just stumbled upon this:

> `m.of(a).chain(f)` is equivalent to `f(a)` (left identity)

now im new to functional programming, so it's probable that i simply dont understand it correctly, but shouldn't that read

`m.of(a).chain(f)` is equivalent to `m.of(f(a))` 

?

Because, say i want an array monad, then this could be specialized to:

```javascript
var f = x => x * 2

Array.of(2) // [2]
Array.of(2).chain(f) // [4]

// but

f(2) // 4

// and therefore
Array.of(2).chain(f).eq(Array.of(f(2))) // true
```

Am i overseeing something?

**Comment by joneshf** [comment]
The law is correct as written, your `f` in the example doesn't have the right type. 

Remember the requirements for [chain](https://github.com/fantasyland/fantasy-land#chain-method), namely:

> 1. f must be a function which returns a value

>     1. If f is not a function, the behaviour of chain is unspecified.
>     1. f must return a value of the same Chain

Here your `f` has type like `f : Number -> Number`, when it needs to have type like `f : Number -> [Number]`. So you've broken the contract for `chain`, thus it doesn't matter what is returned.

If you have the proper type, then things work out.

**Comment by Weitklick** [comment]
Got it, thanks for elaborating!
